### ISSUE TITLE
Deploy error: "failed to deno bundle"

### ISSUE THREAD

**Issue by philcockfield** [hayd/deno-lambda#48] opened 2020-02-02 19:59 UTC
When I run the hello-world sample laid out in the README I'm getting bundle error on aws/now.
Details in the now logs here: https://zeit.co/phil/deno-tmp/f65urnf02

![image](https://user-images.githubusercontent.com/185555/73614380-57627b80-4663-11ea-8f59-7998624fe2ae.png)

I wonder, has something changed upstream in AWS?  Can you guys deploy using this builder to `now` currently, or may I'm doing something stupid.

Thanks - and THANKS for putting this builder together for deno!  This is super helpful to see. 🍰

**Comment by hayd** [comment] 2020-02-03 05:44
Could you include a little more about what you did? Since it's referencing amz-deno I suspect it's a slightly older version of deno-lambda... 🤔 

cc @lucacasonato did I break something on your zeit now? How can we add tests? (happy to help)

_Reminder for me to [add link](https://dev.to/lucacasonato/deno-on-zeit-now-2860) / [link](https://github.com/lucacasonato/now-deno) to the README_

**Comment by hayd** [comment] 2020-02-03 05:48
@lucacasonato This is now `bin/deno` https://github.com/lucacasonato/now-deno/blob/4f5a8010c801ceddf2327fa066f2ab6c0ae0861a/src/index.ts#L133-L136

Although you might prefer/I think it's preferable to use [the SAR application](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:390065572566:applications~deno) which basically creates the base layer (and can be shared across multiple deno applications).

**Comment by philcockfield** [comment] 2020-02-03 07:23
OK, awesome guys - I'll setup a repo and share.

**Comment by philcockfield** [comment] 2020-02-03 07:28
https://github.com/philcockfield/deno-deploy-error-sample

**Comment by lucacasonato** [comment] 2020-02-03 07:51
Hey, haven't updated now-deno for a while. I'll fix it up in a minute. Thanks for letting me know.

**Comment by lucacasonato** [comment] 2020-02-03 09:22
Should be fixed now - please give it a try with now-deno@0.2.0. I really have to implement https://github.com/lucacasonato/now-deno/issues/4 and https://github.com/lucacasonato/now-deno/issues/1.

**Comment by hayd** [comment] 2020-02-03 22:30
@philcockfield is this working for you now?

**Comment by philcockfield** [comment] 2020-02-04 00:29
Baboom! Gentlemen, working on my end.  
Totally fantastic. Thanks so much guys.

**Comment by hayd** [comment] 2020-02-04 01:12
Great!

FYI This was caused by my changes to deno-lambda in #45 #46 so shouldn't occur again.

**Closed by hayd** 2020-02-04 01:12 UTC
